# PDFのビルドとリリースを行うワークフロー
name: Build and Deploy PDF

# mainブランチへのpushに対して実行
on:
  push:
    branches:
      - main
    # .github内が変更されたときは実行しない
    paths-ignore:
      - .github/**

env:
  # 生成するPDFファイルの名前
  ARTIFACT_NAME: main.pdf

# 実行されるジョブの定義
jobs:
  # PDFのビルドジョブ
  build:
    runs-on: ubuntu-22.04

    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Dockerのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Dockerコンテナのビルド
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha

      # Dockerコンテナ内でLaTeXファイルをコンパイルしてPDFを生成
      - name: Compile LaTeX with latexmk inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir texlive-container \
          sh -c "cd tex && latexmk -r .latexmkrc -pdf main.tex"

      # コンパイルされたPDFを確認
      - name: List generated files
        run: |
          echo "Generated files in 'out/pdf' directory:"
          ls -R out/pdf

      # 生成したPDFをGitHub Actionsにアップロード
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: out/pdf/${{ env.ARTIFACT_NAME }}

  # PDFのDeploy
  Deploy-PDF:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # アーティファクトからPDFをダウンロード
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf

      # PDFをGitHub Pagesにデプロイ
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pdf # アーティファクトでダウンロードしたPDFが格納されるディレクトリ
          destination_dir: pdf # デプロイ先フォルダ名
