name: Build and Deploy PDF

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # キャッシュを有効化
      - name: Cache TeX Live
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/texlive
            ~/.texlive*
          key: ${{ runner.os }}-texlive
          restore-keys: |
            ${{ runner.os }}-texlive

      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # TeX Live のインストール (キャッシュがヒットしない場合のみ)
      - name: Setup LaTeX environment
        run: |
          if [ ! -d "/usr/local/texlive" ]; then
            sudo apt-get update
            sudo apt-get install -y texlive-full latexmk biber
          fi

      # latexmkでPDFをコンパイル
      - name: Compile LaTeX with latexmk
        run: |
          latexmk -r .latexmkrc -pdf main.tex

      # コンパイル結果の確認
      - name: List generated files
        run: |
          echo "Generated files in 'out' directory:"
          ls -R out

      # PDFをGitHub Pagesにデプロイ
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out # 生成されたPDFが格納されたディレクトリ
          destination_dir: pdf # デプロイ先フォルダ名
