name: container build

on:
  push:
    branches:
      - main

env:
  # 生成するPDFファイルの名前
  ARTIFACT_NAME: main.pdf

jobs:
  # Docker イメージのビルドとPDF生成ジョブ
  build:
    runs-on: ubuntu-22.04

    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker イメージをキャッシュを活用して高速化してビルド
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: texlive-container:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Docker イメージがビルドされたか確認
      - name: Verify Docker image
        run: |
          echo "Listing Docker images to verify the build:"
          docker images
          if ! docker images | grep -q "texlive-container"; then
            echo "Docker image 'texlive-container:latest' was not built successfully."
            exit 1
          else
            echo "Docker image 'texlive-container:latest' was built successfully."
          fi

      # コンテナを使ってLaTeXファイルをコンパイル
      - name: Compile LaTeX with Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir texlive-container:latest \
          sh -c "cd tex && latexmk -r .latexmkrc -pdf main.tex"

      # コンパイルされたPDFを確認
      - name: List generated files
        run: |
          echo "Generated files in 'out/pdf' directory:"
          ls -R out/pdf

      # 生成したPDFをGitHub Actionsにアップロード
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: out/pdf/${{ env.ARTIFACT_NAME }}
