name: Build and Deploy PDF

on:
  push:
    branches:
      - main

env:
  ARTIFACT_NAME: pdf-artifacts
  PDF_DIR: tex/out/pdf
  TEX_INTERMEDIATES_DIR: tex/out/.tex_intermediates
  PDF_ARTIFACT_PATH: tex/out/pdf/

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # キャッシュの設定
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Docker イメージをビルド
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: texlive-container:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

      # Docker イメージを保存
      - name: Save Docker image
        run: |
          docker save texlive-container:latest -o texlive-container-image.tar

      # Docker イメージをアーティファクトとしてアップロード
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: texlive-container-image
          path: texlive-container-image.tar

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      # リポジトリのソースコードを再度チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # アーティファクトからDockerイメージをダウンロード
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: texlive-container-image
          path: .

      # Docker イメージをロード
      - name: Load Docker image
        run: |
          docker load -i ./texlive-container-image.tar

      # コンテナを起動してPDFを生成
      - name: Run Container to Generate PDF
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            texlive-container:latest \
            bash -c "cd tex && latexmk main.tex"

      # 生成されたPDFを確認
      - name: List Generated PDF files
        run: |
          echo "Generated PDF files:"
          ls -R ${{ env.PDF_DIR }}

      # 生成したPDFをアーティファクトとしてアップロード
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PDF_ARTIFACT_PATH }}
