name: container build

on:
  push:
    branches:
      - main

env:
  # 生成するPDFファイルの名前
  ARTIFACT_NAME: main.pdf

jobs:
  # Docker イメージのビルドとPDF生成ジョブ
  build:
    runs-on: ubuntu-22.04

    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker イメージをビルドしてキャッシュを活用
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/texlive-container:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # コンテナを使ってLaTeXファイルをコンパイル
      - name: Compile LaTeX with Docker container
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/texlive-container:latest
          docker run --rm -v ${{ github.workspace }}:/workdir ghcr.io/${{ github.repository_owner }}/texlive-container:latest \
          sh -c "cd tex && latexmk -r .latexmkrc -pdf main.tex"

      # コンパイルされたPDFを確認
      - name: List generated files
        run: |
          echo "Generated files in 'out/pdf' directory:"
          ls -R out/pdf

      # 生成したPDFをGitHub Actionsにアップロード
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: out/pdf/${{ env.ARTIFACT_NAME }}
